apiVersion: v1
kind: Service
metadata:
  name: sitepadrao
  labels:
    app: sitepadrao
spec:
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 32500
  selector:
    app: sitepadrao
  type: NodePort
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: sitepadrao
spec:
  replicas: 5
  template:
    metadata:
      labels:
        app: sitepadrao
    spec:
      containers:
        - name: app
          image: "127.0.0.1:30400/sitepadrao:latest"
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 5000